/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 * https://bcherny.github.io/json-schema-to-typescript-browser/
 */

/**
 * Build Storybook target options (https://storybook.js.org/configurations/cli-options/)
 */
export interface BuildStorybookSchema {
  /**
   * Target.
   */
  browserTarget: string;
  /**
   * The name of the TypeScript configuration file.
   */
  tsConfig: string;
  /**
   * Global styles to be included in the build.
   */
  staticDir?: string[];
  /**
   * Directory where to store built files
   */
  outputDir: string;
  /**
   * Directory where to load Storybook configurations from
   */
  configDir?: string;
  /**
   * Enable watch mode
   */
  watch?: boolean;
}
