import { AssetPattern, ExtraEntryPoint } from '@angular-devkit/build-angular/src/browser/schema';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 * https://bcherny.github.io/json-schema-to-typescript-browser/
 */

/**
 * Build Storybook target options (https://storybook.js.org/configurations/cli-options/)
 */
export interface BuildStorybookSchema {
  /**
   * List of static application assets.
   */
  assets?: AssetPattern[];
  /**
   * The name of the polyfills file.
   */
  polyfills?: string;
  /**
   * The name of the TypeScript configuration file.
   */
  tsConfig: string;
  /**
   * Global styles to be included in the build.
   */
  styles?: ExtraEntryPoint[];
  /**
   * Directories where to load static files from
   */
  staticDir?: string[];
  /**
   * Directory where to store built files
   */
  outputDir: string;
  /**
   * Directory where to load Storybook configurations from
   */
  configDir?: string;
  /**
   * Enable watch mode
   */
  watch?: boolean;
}

export interface BuildStorybookSchema {}
