/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 * https://bcherny.github.io/json-schema-to-typescript-browser/
 */

import { BuildStorybookSchema } from '../build-storybook/schema';
import { AssetPatternObject } from '@angular-devkit/build-angular';

export interface NormalizedStartStorybookSchema extends StartStorybookSchema {
  assets: AssetPatternObject[];
}

/**
 * Start Storybook target options (https://storybook.js.org/configurations/cli-options/)
 */
export interface StartStorybookSchema extends BuildStorybookSchema {
  /**
   * Target.
   */
  browserTarget: string;
  /**
   * Port to run Storybook
   */
  port?: number;
  /**
   * Host to run Storybook
   */
  host?: string;
  /**
   * Serve Storybook over HTTPS. Note: You must provide your own certificate information.
   */
  https?: boolean;
  /**
   * Provide an SSL certificate. (Required with --https)
   */
  sslCert?: string;
  /**
   * Provide an SSL key. (Required with --https)
   */
  sslKey?: string;
  /**
   * Exit after successful start
   */
  smokeTest?: boolean;
  /**
   * Suppress verbose build output
   */
  quiet?: boolean;
}
